// Code generated by github.com/Khan/genqlient, DO NOT EDIT.

package atcqueries

import (
	"context"
	"time"

	"github.com/Khan/genqlient/graphql"
)

type EthereumNetwork string

const (
	// Ethereum Mainnet
	EthereumNetworkEthereum EthereumNetwork = "ethereum"
	// Ethereum Classic
	EthereumNetworkEthclassic EthereumNetwork = "ethclassic"
	// Ethereum Classic ( no reorg from block 10904146)
	EthereumNetworkEthclassicReorg EthereumNetwork = "ethclassic_reorg"
	// Celo Alfajores Testnet
	EthereumNetworkCeloAlfajores EthereumNetwork = "celo_alfajores"
	// Celo Baklava Testnet
	EthereumNetworkCeloBaklava EthereumNetwork = "celo_baklava"
	// Celo RC1
	EthereumNetworkCeloRc1 EthereumNetwork = "celo_rc1"
	// Binance Smart Chain Mainnet
	EthereumNetworkBsc EthereumNetwork = "bsc"
	// Binance Smart Chain Testnet
	EthereumNetworkBscTestnet EthereumNetwork = "bsc_testnet"
	// Goerli Ethereum Testnet
	EthereumNetworkGoerli EthereumNetwork = "goerli"
	// Matic (Polygon) Mainnet
	EthereumNetworkMatic EthereumNetwork = "matic"
)

// GetTopNDexsForNetworkEthereum includes the requested fields of the GraphQL type Ethereum.
// The GraphQL type's documentation follows.
//
// Ethereum Chain
type GetTopNDexsForNetworkEthereum struct {
	// Trades on Ethereum DEX Smart Contracts
	DexTrades []GetTopNDexsForNetworkEthereumDexTrades `json:"dexTrades"`
}

// GetDexTrades returns GetTopNDexsForNetworkEthereum.DexTrades, and is useful for accessing the field via an interface.
func (v *GetTopNDexsForNetworkEthereum) GetDexTrades() []GetTopNDexsForNetworkEthereumDexTrades {
	return v.DexTrades
}

// GetTopNDexsForNetworkEthereumDexTrades includes the requested fields of the GraphQL type EthereumDexTrades.
// The GraphQL type's documentation follows.
//
// Trades on DEX smart contracts
type GetTopNDexsForNetworkEthereumDexTrades struct {
	// Protocol name of the smart contract
	Protocol   string `json:"protocol"`
	Trades     int    `json:"trades"`
	Currencies int    `json:"currencies"`
	Contracts  int    `json:"contracts"`
	// Identification of admin / manager / factory of smart contract, executing trades
	Exchange GetTopNDexsForNetworkEthereumDexTradesExchangeEthereumDex `json:"exchange"`
}

// GetProtocol returns GetTopNDexsForNetworkEthereumDexTrades.Protocol, and is useful for accessing the field via an interface.
func (v *GetTopNDexsForNetworkEthereumDexTrades) GetProtocol() string { return v.Protocol }

// GetTrades returns GetTopNDexsForNetworkEthereumDexTrades.Trades, and is useful for accessing the field via an interface.
func (v *GetTopNDexsForNetworkEthereumDexTrades) GetTrades() int { return v.Trades }

// GetCurrencies returns GetTopNDexsForNetworkEthereumDexTrades.Currencies, and is useful for accessing the field via an interface.
func (v *GetTopNDexsForNetworkEthereumDexTrades) GetCurrencies() int { return v.Currencies }

// GetContracts returns GetTopNDexsForNetworkEthereumDexTrades.Contracts, and is useful for accessing the field via an interface.
func (v *GetTopNDexsForNetworkEthereumDexTrades) GetContracts() int { return v.Contracts }

// GetExchange returns GetTopNDexsForNetworkEthereumDexTrades.Exchange, and is useful for accessing the field via an interface.
func (v *GetTopNDexsForNetworkEthereumDexTrades) GetExchange() GetTopNDexsForNetworkEthereumDexTradesExchangeEthereumDex {
	return v.Exchange
}

// GetTopNDexsForNetworkEthereumDexTradesExchangeEthereumDex includes the requested fields of the GraphQL type EthereumDex.
// The GraphQL type's documentation follows.
//
// Ethereum DEX attributes
type GetTopNDexsForNetworkEthereumDexTradesExchangeEthereumDex struct {
	// Full name ( name for known, Protocol for unknown )
	FullName string `json:"fullName"`
	// Address for DEX exchange identification
	Address GetTopNDexsForNetworkEthereumDexTradesExchangeEthereumDexAddress `json:"address"`
}

// GetFullName returns GetTopNDexsForNetworkEthereumDexTradesExchangeEthereumDex.FullName, and is useful for accessing the field via an interface.
func (v *GetTopNDexsForNetworkEthereumDexTradesExchangeEthereumDex) GetFullName() string {
	return v.FullName
}

// GetAddress returns GetTopNDexsForNetworkEthereumDexTradesExchangeEthereumDex.Address, and is useful for accessing the field via an interface.
func (v *GetTopNDexsForNetworkEthereumDexTradesExchangeEthereumDex) GetAddress() GetTopNDexsForNetworkEthereumDexTradesExchangeEthereumDexAddress {
	return v.Address
}

// GetTopNDexsForNetworkEthereumDexTradesExchangeEthereumDexAddress includes the requested fields of the GraphQL type Address.
// The GraphQL type's documentation follows.
//
// Blockchain address
type GetTopNDexsForNetworkEthereumDexTradesExchangeEthereumDexAddress struct {
	// String address representation
	Address string `json:"address"`
}

// GetAddress returns GetTopNDexsForNetworkEthereumDexTradesExchangeEthereumDexAddress.Address, and is useful for accessing the field via an interface.
func (v *GetTopNDexsForNetworkEthereumDexTradesExchangeEthereumDexAddress) GetAddress() string {
	return v.Address
}

// GetTopNDexsForNetworkResponse is returned by GetTopNDexsForNetwork on success.
type GetTopNDexsForNetworkResponse struct {
	// Ethereum Mainnet / Classic Chain Datasets
	Ethereum GetTopNDexsForNetworkEthereum `json:"ethereum"`
}

// GetEthereum returns GetTopNDexsForNetworkResponse.Ethereum, and is useful for accessing the field via an interface.
func (v *GetTopNDexsForNetworkResponse) GetEthereum() GetTopNDexsForNetworkEthereum {
	return v.Ethereum
}

// __GetTopNDexsForNetworkInput is used internally by genqlient
type __GetTopNDexsForNetworkInput struct {
	Network EthereumNetwork `json:"network"`
	Limit   int             `json:"limit"`
	Offset  int             `json:"offset"`
	From    time.Time       `json:"from"`
}

// GetNetwork returns __GetTopNDexsForNetworkInput.Network, and is useful for accessing the field via an interface.
func (v *__GetTopNDexsForNetworkInput) GetNetwork() EthereumNetwork { return v.Network }

// GetLimit returns __GetTopNDexsForNetworkInput.Limit, and is useful for accessing the field via an interface.
func (v *__GetTopNDexsForNetworkInput) GetLimit() int { return v.Limit }

// GetOffset returns __GetTopNDexsForNetworkInput.Offset, and is useful for accessing the field via an interface.
func (v *__GetTopNDexsForNetworkInput) GetOffset() int { return v.Offset }

// GetFrom returns __GetTopNDexsForNetworkInput.From, and is useful for accessing the field via an interface.
func (v *__GetTopNDexsForNetworkInput) GetFrom() time.Time { return v.From }

func GetTopNDexsForNetwork(
	ctx context.Context,
	client graphql.Client,
	network EthereumNetwork,
	limit int,
	offset int,
	from time.Time,
) (*GetTopNDexsForNetworkResponse, error) {
	req := &graphql.Request{
		OpName: "GetTopNDexsForNetwork",
		Query: `
query GetTopNDexsForNetwork ($network: EthereumNetwork!, $limit: Int!, $offset: Int!, $from: ISO8601DateTime) {
	ethereum(network: $network) {
		dexTrades(options: {desc:"trades",limit:$limit,offset:$offset}, date: {since:$from}, protocol: {is:"Uniswap v2"}) {
			protocol
			trades: count
			currencies: count(uniq: buy_currency)
			contracts: count(uniq: smart_contracts)
			exchange {
				fullName
				address {
					address
				}
			}
		}
	}
}
`,
		Variables: &__GetTopNDexsForNetworkInput{
			Network: network,
			Limit:   limit,
			Offset:  offset,
			From:    from,
		},
	}
	var err error

	var data GetTopNDexsForNetworkResponse
	resp := &graphql.Response{Data: &data}

	err = client.MakeRequest(
		ctx,
		req,
		resp,
	)

	return &data, err
}
