// Code generated by github.com/Khan/genqlient, DO NOT EDIT.

package atcqueries

import (
	"context"
	"time"

	"github.com/Khan/genqlient/graphql"
)

type EthereumNetwork string

const (
	// Ethereum Mainnet
	EthereumNetworkEthereum EthereumNetwork = "ethereum"
	// Ethereum Classic
	EthereumNetworkEthclassic EthereumNetwork = "ethclassic"
	// Ethereum Classic ( no reorg from block 10904146)
	EthereumNetworkEthclassicReorg EthereumNetwork = "ethclassic_reorg"
	// Celo Alfajores Testnet
	EthereumNetworkCeloAlfajores EthereumNetwork = "celo_alfajores"
	// Celo Baklava Testnet
	EthereumNetworkCeloBaklava EthereumNetwork = "celo_baklava"
	// Celo RC1
	EthereumNetworkCeloRc1 EthereumNetwork = "celo_rc1"
	// Binance Smart Chain Mainnet
	EthereumNetworkBsc EthereumNetwork = "bsc"
	// Binance Smart Chain Testnet
	EthereumNetworkBscTestnet EthereumNetwork = "bsc_testnet"
	// Goerli Ethereum Testnet
	EthereumNetworkGoerli EthereumNetwork = "goerli"
	// Matic (Polygon) Mainnet
	EthereumNetworkMatic EthereumNetwork = "matic"
)

// GetAllStablecoinPairsCreatedForDexEthereum includes the requested fields of the GraphQL type Ethereum.
// The GraphQL type's documentation follows.
//
// Ethereum Chain
type GetAllStablecoinPairsCreatedForDexEthereum struct {
	// Trades on Ethereum DEX Smart Contracts
	DexTrades []GetAllStablecoinPairsCreatedForDexEthereumDexTrades `json:"dexTrades"`
}

// GetDexTrades returns GetAllStablecoinPairsCreatedForDexEthereum.DexTrades, and is useful for accessing the field via an interface.
func (v *GetAllStablecoinPairsCreatedForDexEthereum) GetDexTrades() []GetAllStablecoinPairsCreatedForDexEthereumDexTrades {
	return v.DexTrades
}

// GetAllStablecoinPairsCreatedForDexEthereumDexTrades includes the requested fields of the GraphQL type EthereumDexTrades.
// The GraphQL type's documentation follows.
//
// Trades on DEX smart contracts
type GetAllStablecoinPairsCreatedForDexEthereumDexTrades struct {
	// Time interval
	TimeInterval GetAllStablecoinPairsCreatedForDexEthereumDexTradesTimeInterval `json:"timeInterval"`
	// Base currency
	BaseCurrency GetAllStablecoinPairsCreatedForDexEthereumDexTradesBaseCurrency `json:"baseCurrency"`
	BaseAmount   float64                                                         `json:"baseAmount"`
	// Quote currency
	QuoteCurrency GetAllStablecoinPairsCreatedForDexEthereumDexTradesQuoteCurrency `json:"quoteCurrency"`
	QuoteAmount   float64                                                          `json:"quoteAmount"`
	Trades        int                                                              `json:"trades"`
	QuotePrice    float64                                                          `json:"quotePrice"`
	High          float64                                                          `json:"high"`
	Low           float64                                                          `json:"low"`
	Open          string                                                           `json:"open"`
	Close         string                                                           `json:"close"`
	Volume        float64                                                          `json:"volume"`
	Count         int                                                              `json:"count"`
}

// GetTimeInterval returns GetAllStablecoinPairsCreatedForDexEthereumDexTrades.TimeInterval, and is useful for accessing the field via an interface.
func (v *GetAllStablecoinPairsCreatedForDexEthereumDexTrades) GetTimeInterval() GetAllStablecoinPairsCreatedForDexEthereumDexTradesTimeInterval {
	return v.TimeInterval
}

// GetBaseCurrency returns GetAllStablecoinPairsCreatedForDexEthereumDexTrades.BaseCurrency, and is useful for accessing the field via an interface.
func (v *GetAllStablecoinPairsCreatedForDexEthereumDexTrades) GetBaseCurrency() GetAllStablecoinPairsCreatedForDexEthereumDexTradesBaseCurrency {
	return v.BaseCurrency
}

// GetBaseAmount returns GetAllStablecoinPairsCreatedForDexEthereumDexTrades.BaseAmount, and is useful for accessing the field via an interface.
func (v *GetAllStablecoinPairsCreatedForDexEthereumDexTrades) GetBaseAmount() float64 {
	return v.BaseAmount
}

// GetQuoteCurrency returns GetAllStablecoinPairsCreatedForDexEthereumDexTrades.QuoteCurrency, and is useful for accessing the field via an interface.
func (v *GetAllStablecoinPairsCreatedForDexEthereumDexTrades) GetQuoteCurrency() GetAllStablecoinPairsCreatedForDexEthereumDexTradesQuoteCurrency {
	return v.QuoteCurrency
}

// GetQuoteAmount returns GetAllStablecoinPairsCreatedForDexEthereumDexTrades.QuoteAmount, and is useful for accessing the field via an interface.
func (v *GetAllStablecoinPairsCreatedForDexEthereumDexTrades) GetQuoteAmount() float64 {
	return v.QuoteAmount
}

// GetTrades returns GetAllStablecoinPairsCreatedForDexEthereumDexTrades.Trades, and is useful for accessing the field via an interface.
func (v *GetAllStablecoinPairsCreatedForDexEthereumDexTrades) GetTrades() int { return v.Trades }

// GetQuotePrice returns GetAllStablecoinPairsCreatedForDexEthereumDexTrades.QuotePrice, and is useful for accessing the field via an interface.
func (v *GetAllStablecoinPairsCreatedForDexEthereumDexTrades) GetQuotePrice() float64 {
	return v.QuotePrice
}

// GetHigh returns GetAllStablecoinPairsCreatedForDexEthereumDexTrades.High, and is useful for accessing the field via an interface.
func (v *GetAllStablecoinPairsCreatedForDexEthereumDexTrades) GetHigh() float64 { return v.High }

// GetLow returns GetAllStablecoinPairsCreatedForDexEthereumDexTrades.Low, and is useful for accessing the field via an interface.
func (v *GetAllStablecoinPairsCreatedForDexEthereumDexTrades) GetLow() float64 { return v.Low }

// GetOpen returns GetAllStablecoinPairsCreatedForDexEthereumDexTrades.Open, and is useful for accessing the field via an interface.
func (v *GetAllStablecoinPairsCreatedForDexEthereumDexTrades) GetOpen() string { return v.Open }

// GetClose returns GetAllStablecoinPairsCreatedForDexEthereumDexTrades.Close, and is useful for accessing the field via an interface.
func (v *GetAllStablecoinPairsCreatedForDexEthereumDexTrades) GetClose() string { return v.Close }

// GetVolume returns GetAllStablecoinPairsCreatedForDexEthereumDexTrades.Volume, and is useful for accessing the field via an interface.
func (v *GetAllStablecoinPairsCreatedForDexEthereumDexTrades) GetVolume() float64 { return v.Volume }

// GetCount returns GetAllStablecoinPairsCreatedForDexEthereumDexTrades.Count, and is useful for accessing the field via an interface.
func (v *GetAllStablecoinPairsCreatedForDexEthereumDexTrades) GetCount() int { return v.Count }

// GetAllStablecoinPairsCreatedForDexEthereumDexTradesBaseCurrency includes the requested fields of the GraphQL type Currency.
// The GraphQL type's documentation follows.
//
// Crypto currency ( token, coin, currency )
type GetAllStablecoinPairsCreatedForDexEthereumDexTradesBaseCurrency struct {
	// Currency symbol
	Symbol string `json:"symbol"`
	// Token Smart Contract Address
	Address string `json:"address"`
}

// GetSymbol returns GetAllStablecoinPairsCreatedForDexEthereumDexTradesBaseCurrency.Symbol, and is useful for accessing the field via an interface.
func (v *GetAllStablecoinPairsCreatedForDexEthereumDexTradesBaseCurrency) GetSymbol() string {
	return v.Symbol
}

// GetAddress returns GetAllStablecoinPairsCreatedForDexEthereumDexTradesBaseCurrency.Address, and is useful for accessing the field via an interface.
func (v *GetAllStablecoinPairsCreatedForDexEthereumDexTradesBaseCurrency) GetAddress() string {
	return v.Address
}

// GetAllStablecoinPairsCreatedForDexEthereumDexTradesQuoteCurrency includes the requested fields of the GraphQL type Currency.
// The GraphQL type's documentation follows.
//
// Crypto currency ( token, coin, currency )
type GetAllStablecoinPairsCreatedForDexEthereumDexTradesQuoteCurrency struct {
	// Currency symbol
	Symbol string `json:"symbol"`
	// Token Smart Contract Address
	Address string `json:"address"`
}

// GetSymbol returns GetAllStablecoinPairsCreatedForDexEthereumDexTradesQuoteCurrency.Symbol, and is useful for accessing the field via an interface.
func (v *GetAllStablecoinPairsCreatedForDexEthereumDexTradesQuoteCurrency) GetSymbol() string {
	return v.Symbol
}

// GetAddress returns GetAllStablecoinPairsCreatedForDexEthereumDexTradesQuoteCurrency.Address, and is useful for accessing the field via an interface.
func (v *GetAllStablecoinPairsCreatedForDexEthereumDexTradesQuoteCurrency) GetAddress() string {
	return v.Address
}

// GetAllStablecoinPairsCreatedForDexEthereumDexTradesTimeInterval includes the requested fields of the GraphQL type TimeInterval.
// The GraphQL type's documentation follows.
//
// Time Interval
type GetAllStablecoinPairsCreatedForDexEthereumDexTradesTimeInterval struct {
	Second string `json:"second"`
}

// GetSecond returns GetAllStablecoinPairsCreatedForDexEthereumDexTradesTimeInterval.Second, and is useful for accessing the field via an interface.
func (v *GetAllStablecoinPairsCreatedForDexEthereumDexTradesTimeInterval) GetSecond() string {
	return v.Second
}

// GetAllStablecoinPairsCreatedForDexResponse is returned by GetAllStablecoinPairsCreatedForDex on success.
type GetAllStablecoinPairsCreatedForDexResponse struct {
	// Ethereum Mainnet / Classic Chain Datasets
	Ethereum GetAllStablecoinPairsCreatedForDexEthereum `json:"ethereum"`
}

// GetEthereum returns GetAllStablecoinPairsCreatedForDexResponse.Ethereum, and is useful for accessing the field via an interface.
func (v *GetAllStablecoinPairsCreatedForDexResponse) GetEthereum() GetAllStablecoinPairsCreatedForDexEthereum {
	return v.Ethereum
}

// GetBitQueryAccountDetailsResponse is returned by GetBitQueryAccountDetails on success.
type GetBitQueryAccountDetailsResponse struct {
	// Utility Dataset
	Utilities GetBitQueryAccountDetailsUtilitiesUtility `json:"utilities"`
}

// GetUtilities returns GetBitQueryAccountDetailsResponse.Utilities, and is useful for accessing the field via an interface.
func (v *GetBitQueryAccountDetailsResponse) GetUtilities() GetBitQueryAccountDetailsUtilitiesUtility {
	return v.Utilities
}

// GetBitQueryAccountDetailsUtilitiesUtility includes the requested fields of the GraphQL type Utility.
type GetBitQueryAccountDetailsUtilitiesUtility struct {
	// Trades on Ethereum DEX Smart Contracts
	ActivePeriod GetBitQueryAccountDetailsUtilitiesUtilityActivePeriodBitqueryAccountInfo `json:"activePeriod"`
}

// GetActivePeriod returns GetBitQueryAccountDetailsUtilitiesUtility.ActivePeriod, and is useful for accessing the field via an interface.
func (v *GetBitQueryAccountDetailsUtilitiesUtility) GetActivePeriod() GetBitQueryAccountDetailsUtilitiesUtilityActivePeriodBitqueryAccountInfo {
	return v.ActivePeriod
}

// GetBitQueryAccountDetailsUtilitiesUtilityActivePeriodBitqueryAccountInfo includes the requested fields of the GraphQL type BitqueryAccountInfo.
// The GraphQL type's documentation follows.
//
// Bitquery Account Info
type GetBitQueryAccountDetailsUtilitiesUtilityActivePeriodBitqueryAccountInfo struct {
	PointsRemaining  string                                                                             `json:"pointsRemaining"`
	Points           string                                                                             `json:"points"`
	IsPaid           bool                                                                               `json:"isPaid"`
	IsPointsConsumed bool                                                                               `json:"isPointsConsumed"`
	IsSpent          bool                                                                               `json:"isSpent"`
	IsBlocked        bool                                                                               `json:"isBlocked"`
	Starts           GetBitQueryAccountDetailsUtilitiesUtilityActivePeriodBitqueryAccountInfoStartsDate `json:"starts"`
	Ends             GetBitQueryAccountDetailsUtilitiesUtilityActivePeriodBitqueryAccountInfoEndsDate   `json:"ends"`
	BillingDay       int                                                                                `json:"billingDay"`
}

// GetPointsRemaining returns GetBitQueryAccountDetailsUtilitiesUtilityActivePeriodBitqueryAccountInfo.PointsRemaining, and is useful for accessing the field via an interface.
func (v *GetBitQueryAccountDetailsUtilitiesUtilityActivePeriodBitqueryAccountInfo) GetPointsRemaining() string {
	return v.PointsRemaining
}

// GetPoints returns GetBitQueryAccountDetailsUtilitiesUtilityActivePeriodBitqueryAccountInfo.Points, and is useful for accessing the field via an interface.
func (v *GetBitQueryAccountDetailsUtilitiesUtilityActivePeriodBitqueryAccountInfo) GetPoints() string {
	return v.Points
}

// GetIsPaid returns GetBitQueryAccountDetailsUtilitiesUtilityActivePeriodBitqueryAccountInfo.IsPaid, and is useful for accessing the field via an interface.
func (v *GetBitQueryAccountDetailsUtilitiesUtilityActivePeriodBitqueryAccountInfo) GetIsPaid() bool {
	return v.IsPaid
}

// GetIsPointsConsumed returns GetBitQueryAccountDetailsUtilitiesUtilityActivePeriodBitqueryAccountInfo.IsPointsConsumed, and is useful for accessing the field via an interface.
func (v *GetBitQueryAccountDetailsUtilitiesUtilityActivePeriodBitqueryAccountInfo) GetIsPointsConsumed() bool {
	return v.IsPointsConsumed
}

// GetIsSpent returns GetBitQueryAccountDetailsUtilitiesUtilityActivePeriodBitqueryAccountInfo.IsSpent, and is useful for accessing the field via an interface.
func (v *GetBitQueryAccountDetailsUtilitiesUtilityActivePeriodBitqueryAccountInfo) GetIsSpent() bool {
	return v.IsSpent
}

// GetIsBlocked returns GetBitQueryAccountDetailsUtilitiesUtilityActivePeriodBitqueryAccountInfo.IsBlocked, and is useful for accessing the field via an interface.
func (v *GetBitQueryAccountDetailsUtilitiesUtilityActivePeriodBitqueryAccountInfo) GetIsBlocked() bool {
	return v.IsBlocked
}

// GetStarts returns GetBitQueryAccountDetailsUtilitiesUtilityActivePeriodBitqueryAccountInfo.Starts, and is useful for accessing the field via an interface.
func (v *GetBitQueryAccountDetailsUtilitiesUtilityActivePeriodBitqueryAccountInfo) GetStarts() GetBitQueryAccountDetailsUtilitiesUtilityActivePeriodBitqueryAccountInfoStartsDate {
	return v.Starts
}

// GetEnds returns GetBitQueryAccountDetailsUtilitiesUtilityActivePeriodBitqueryAccountInfo.Ends, and is useful for accessing the field via an interface.
func (v *GetBitQueryAccountDetailsUtilitiesUtilityActivePeriodBitqueryAccountInfo) GetEnds() GetBitQueryAccountDetailsUtilitiesUtilityActivePeriodBitqueryAccountInfoEndsDate {
	return v.Ends
}

// GetBillingDay returns GetBitQueryAccountDetailsUtilitiesUtilityActivePeriodBitqueryAccountInfo.BillingDay, and is useful for accessing the field via an interface.
func (v *GetBitQueryAccountDetailsUtilitiesUtilityActivePeriodBitqueryAccountInfo) GetBillingDay() int {
	return v.BillingDay
}

// GetBitQueryAccountDetailsUtilitiesUtilityActivePeriodBitqueryAccountInfoEndsDate includes the requested fields of the GraphQL type Date.
// The GraphQL type's documentation follows.
//
// Date
type GetBitQueryAccountDetailsUtilitiesUtilityActivePeriodBitqueryAccountInfoEndsDate struct {
	// String date representation with default format as YYYY-MM-DD
	Date string `json:"date"`
}

// GetDate returns GetBitQueryAccountDetailsUtilitiesUtilityActivePeriodBitqueryAccountInfoEndsDate.Date, and is useful for accessing the field via an interface.
func (v *GetBitQueryAccountDetailsUtilitiesUtilityActivePeriodBitqueryAccountInfoEndsDate) GetDate() string {
	return v.Date
}

// GetBitQueryAccountDetailsUtilitiesUtilityActivePeriodBitqueryAccountInfoStartsDate includes the requested fields of the GraphQL type Date.
// The GraphQL type's documentation follows.
//
// Date
type GetBitQueryAccountDetailsUtilitiesUtilityActivePeriodBitqueryAccountInfoStartsDate struct {
	// String date representation with default format as YYYY-MM-DD
	Date string `json:"date"`
}

// GetDate returns GetBitQueryAccountDetailsUtilitiesUtilityActivePeriodBitqueryAccountInfoStartsDate.Date, and is useful for accessing the field via an interface.
func (v *GetBitQueryAccountDetailsUtilitiesUtilityActivePeriodBitqueryAccountInfoStartsDate) GetDate() string {
	return v.Date
}

// GetPairCreatedByFactoryEthereum includes the requested fields of the GraphQL type Ethereum.
// The GraphQL type's documentation follows.
//
// Ethereum Chain
type GetPairCreatedByFactoryEthereum struct {
	// Arguments of Smart Contract Calls and Events
	Arguments []GetPairCreatedByFactoryEthereumArguments `json:"arguments"`
}

// GetArguments returns GetPairCreatedByFactoryEthereum.Arguments, and is useful for accessing the field via an interface.
func (v *GetPairCreatedByFactoryEthereum) GetArguments() []GetPairCreatedByFactoryEthereumArguments {
	return v.Arguments
}

// GetPairCreatedByFactoryEthereumArguments includes the requested fields of the GraphQL type EthereumArguments.
// The GraphQL type's documentation follows.
//
// Arguments of Smart Contract Calls and Events
type GetPairCreatedByFactoryEthereumArguments struct {
	// Address value of method or event argument
	Reference GetPairCreatedByFactoryEthereumArgumentsReferenceEthereumAddressInfo `json:"reference"`
	// Block in the blockchain
	Block GetPairCreatedByFactoryEthereumArgumentsBlock `json:"block"`
}

// GetReference returns GetPairCreatedByFactoryEthereumArguments.Reference, and is useful for accessing the field via an interface.
func (v *GetPairCreatedByFactoryEthereumArguments) GetReference() GetPairCreatedByFactoryEthereumArgumentsReferenceEthereumAddressInfo {
	return v.Reference
}

// GetBlock returns GetPairCreatedByFactoryEthereumArguments.Block, and is useful for accessing the field via an interface.
func (v *GetPairCreatedByFactoryEthereumArguments) GetBlock() GetPairCreatedByFactoryEthereumArgumentsBlock {
	return v.Block
}

// GetPairCreatedByFactoryEthereumArgumentsBlock includes the requested fields of the GraphQL type Block.
// The GraphQL type's documentation follows.
//
// Block
type GetPairCreatedByFactoryEthereumArgumentsBlock struct {
	// Block number (height) in blockchain
	Height int `json:"height"`
}

// GetHeight returns GetPairCreatedByFactoryEthereumArgumentsBlock.Height, and is useful for accessing the field via an interface.
func (v *GetPairCreatedByFactoryEthereumArgumentsBlock) GetHeight() int { return v.Height }

// GetPairCreatedByFactoryEthereumArgumentsReferenceEthereumAddressInfo includes the requested fields of the GraphQL type EthereumAddressInfo.
// The GraphQL type's documentation follows.
//
// Address detailed information for Ethereum network
type GetPairCreatedByFactoryEthereumArgumentsReferenceEthereumAddressInfo struct {
	// String address representation
	Address string `json:"address"`
}

// GetAddress returns GetPairCreatedByFactoryEthereumArgumentsReferenceEthereumAddressInfo.Address, and is useful for accessing the field via an interface.
func (v *GetPairCreatedByFactoryEthereumArgumentsReferenceEthereumAddressInfo) GetAddress() string {
	return v.Address
}

// GetPairCreatedByFactoryResponse is returned by GetPairCreatedByFactory on success.
type GetPairCreatedByFactoryResponse struct {
	// Ethereum Mainnet / Classic Chain Datasets
	Ethereum GetPairCreatedByFactoryEthereum `json:"ethereum"`
}

// GetEthereum returns GetPairCreatedByFactoryResponse.Ethereum, and is useful for accessing the field via an interface.
func (v *GetPairCreatedByFactoryResponse) GetEthereum() GetPairCreatedByFactoryEthereum {
	return v.Ethereum
}

// GetRouterAddressFromPairBaseCurrencysEthereum includes the requested fields of the GraphQL type Ethereum.
// The GraphQL type's documentation follows.
//
// Ethereum Chain
type GetRouterAddressFromPairBaseCurrencysEthereum struct {
	// Trades on Ethereum DEX Smart Contracts
	DexTrades []GetRouterAddressFromPairBaseCurrencysEthereumDexTrades `json:"dexTrades"`
}

// GetDexTrades returns GetRouterAddressFromPairBaseCurrencysEthereum.DexTrades, and is useful for accessing the field via an interface.
func (v *GetRouterAddressFromPairBaseCurrencysEthereum) GetDexTrades() []GetRouterAddressFromPairBaseCurrencysEthereumDexTrades {
	return v.DexTrades
}

// GetRouterAddressFromPairBaseCurrencysEthereumDexTrades includes the requested fields of the GraphQL type EthereumDexTrades.
// The GraphQL type's documentation follows.
//
// Trades on DEX smart contracts
type GetRouterAddressFromPairBaseCurrencysEthereumDexTrades struct {
	// Block in the blockchain
	Block GetRouterAddressFromPairBaseCurrencysEthereumDexTradesBlockBlockExtended `json:"block"`
	// Transaction of DexTrade
	Transaction GetRouterAddressFromPairBaseCurrencysEthereumDexTradesTransactionEthereumTransactionInfoExtended `json:"transaction"`
}

// GetBlock returns GetRouterAddressFromPairBaseCurrencysEthereumDexTrades.Block, and is useful for accessing the field via an interface.
func (v *GetRouterAddressFromPairBaseCurrencysEthereumDexTrades) GetBlock() GetRouterAddressFromPairBaseCurrencysEthereumDexTradesBlockBlockExtended {
	return v.Block
}

// GetTransaction returns GetRouterAddressFromPairBaseCurrencysEthereumDexTrades.Transaction, and is useful for accessing the field via an interface.
func (v *GetRouterAddressFromPairBaseCurrencysEthereumDexTrades) GetTransaction() GetRouterAddressFromPairBaseCurrencysEthereumDexTradesTransactionEthereumTransactionInfoExtended {
	return v.Transaction
}

// GetRouterAddressFromPairBaseCurrencysEthereumDexTradesBlockBlockExtended includes the requested fields of the GraphQL type BlockExtended.
// The GraphQL type's documentation follows.
//
// BlockExtended
type GetRouterAddressFromPairBaseCurrencysEthereumDexTradesBlockBlockExtended struct {
	// Block number (height) in blockchain
	Height int `json:"height"`
}

// GetHeight returns GetRouterAddressFromPairBaseCurrencysEthereumDexTradesBlockBlockExtended.Height, and is useful for accessing the field via an interface.
func (v *GetRouterAddressFromPairBaseCurrencysEthereumDexTradesBlockBlockExtended) GetHeight() int {
	return v.Height
}

// GetRouterAddressFromPairBaseCurrencysEthereumDexTradesTransactionEthereumTransactionInfoExtended includes the requested fields of the GraphQL type EthereumTransactionInfoExtended.
// The GraphQL type's documentation follows.
//
// Blockchain Transaction Extended info
type GetRouterAddressFromPairBaseCurrencysEthereumDexTradesTransactionEthereumTransactionInfoExtended struct {
	// Transaction receiver
	To GetRouterAddressFromPairBaseCurrencysEthereumDexTradesTransactionEthereumTransactionInfoExtendedToEthereumAddressInfo `json:"to"`
}

// GetTo returns GetRouterAddressFromPairBaseCurrencysEthereumDexTradesTransactionEthereumTransactionInfoExtended.To, and is useful for accessing the field via an interface.
func (v *GetRouterAddressFromPairBaseCurrencysEthereumDexTradesTransactionEthereumTransactionInfoExtended) GetTo() GetRouterAddressFromPairBaseCurrencysEthereumDexTradesTransactionEthereumTransactionInfoExtendedToEthereumAddressInfo {
	return v.To
}

// GetRouterAddressFromPairBaseCurrencysEthereumDexTradesTransactionEthereumTransactionInfoExtendedToEthereumAddressInfo includes the requested fields of the GraphQL type EthereumAddressInfo.
// The GraphQL type's documentation follows.
//
// Address detailed information for Ethereum network
type GetRouterAddressFromPairBaseCurrencysEthereumDexTradesTransactionEthereumTransactionInfoExtendedToEthereumAddressInfo struct {
	// String address representation
	Address string `json:"address"`
}

// GetAddress returns GetRouterAddressFromPairBaseCurrencysEthereumDexTradesTransactionEthereumTransactionInfoExtendedToEthereumAddressInfo.Address, and is useful for accessing the field via an interface.
func (v *GetRouterAddressFromPairBaseCurrencysEthereumDexTradesTransactionEthereumTransactionInfoExtendedToEthereumAddressInfo) GetAddress() string {
	return v.Address
}

// GetRouterAddressFromPairBaseCurrencysResponse is returned by GetRouterAddressFromPairBaseCurrencys on success.
type GetRouterAddressFromPairBaseCurrencysResponse struct {
	// Ethereum Mainnet / Classic Chain Datasets
	Ethereum GetRouterAddressFromPairBaseCurrencysEthereum `json:"ethereum"`
}

// GetEthereum returns GetRouterAddressFromPairBaseCurrencysResponse.Ethereum, and is useful for accessing the field via an interface.
func (v *GetRouterAddressFromPairBaseCurrencysResponse) GetEthereum() GetRouterAddressFromPairBaseCurrencysEthereum {
	return v.Ethereum
}

// GetTopNDexsForNetworkEthereum includes the requested fields of the GraphQL type Ethereum.
// The GraphQL type's documentation follows.
//
// Ethereum Chain
type GetTopNDexsForNetworkEthereum struct {
	// Trades on Ethereum DEX Smart Contracts
	DexTrades []GetTopNDexsForNetworkEthereumDexTrades `json:"dexTrades"`
}

// GetDexTrades returns GetTopNDexsForNetworkEthereum.DexTrades, and is useful for accessing the field via an interface.
func (v *GetTopNDexsForNetworkEthereum) GetDexTrades() []GetTopNDexsForNetworkEthereumDexTrades {
	return v.DexTrades
}

// GetTopNDexsForNetworkEthereumDexTrades includes the requested fields of the GraphQL type EthereumDexTrades.
// The GraphQL type's documentation follows.
//
// Trades on DEX smart contracts
type GetTopNDexsForNetworkEthereumDexTrades struct {
	// Protocol name of the smart contract
	Protocol   string `json:"protocol"`
	Trades     int    `json:"trades"`
	Currencies int    `json:"currencies"`
	Contracts  int    `json:"contracts"`
	// Identification of admin / manager / factory of smart contract, executing trades
	Exchange GetTopNDexsForNetworkEthereumDexTradesExchangeEthereumDex `json:"exchange"`
}

// GetProtocol returns GetTopNDexsForNetworkEthereumDexTrades.Protocol, and is useful for accessing the field via an interface.
func (v *GetTopNDexsForNetworkEthereumDexTrades) GetProtocol() string { return v.Protocol }

// GetTrades returns GetTopNDexsForNetworkEthereumDexTrades.Trades, and is useful for accessing the field via an interface.
func (v *GetTopNDexsForNetworkEthereumDexTrades) GetTrades() int { return v.Trades }

// GetCurrencies returns GetTopNDexsForNetworkEthereumDexTrades.Currencies, and is useful for accessing the field via an interface.
func (v *GetTopNDexsForNetworkEthereumDexTrades) GetCurrencies() int { return v.Currencies }

// GetContracts returns GetTopNDexsForNetworkEthereumDexTrades.Contracts, and is useful for accessing the field via an interface.
func (v *GetTopNDexsForNetworkEthereumDexTrades) GetContracts() int { return v.Contracts }

// GetExchange returns GetTopNDexsForNetworkEthereumDexTrades.Exchange, and is useful for accessing the field via an interface.
func (v *GetTopNDexsForNetworkEthereumDexTrades) GetExchange() GetTopNDexsForNetworkEthereumDexTradesExchangeEthereumDex {
	return v.Exchange
}

// GetTopNDexsForNetworkEthereumDexTradesExchangeEthereumDex includes the requested fields of the GraphQL type EthereumDex.
// The GraphQL type's documentation follows.
//
// Ethereum DEX attributes
type GetTopNDexsForNetworkEthereumDexTradesExchangeEthereumDex struct {
	// Full name ( name for known, Protocol for unknown )
	FullName string `json:"fullName"`
	// Address for DEX exchange identification
	Address GetTopNDexsForNetworkEthereumDexTradesExchangeEthereumDexAddress `json:"address"`
}

// GetFullName returns GetTopNDexsForNetworkEthereumDexTradesExchangeEthereumDex.FullName, and is useful for accessing the field via an interface.
func (v *GetTopNDexsForNetworkEthereumDexTradesExchangeEthereumDex) GetFullName() string {
	return v.FullName
}

// GetAddress returns GetTopNDexsForNetworkEthereumDexTradesExchangeEthereumDex.Address, and is useful for accessing the field via an interface.
func (v *GetTopNDexsForNetworkEthereumDexTradesExchangeEthereumDex) GetAddress() GetTopNDexsForNetworkEthereumDexTradesExchangeEthereumDexAddress {
	return v.Address
}

// GetTopNDexsForNetworkEthereumDexTradesExchangeEthereumDexAddress includes the requested fields of the GraphQL type Address.
// The GraphQL type's documentation follows.
//
// Blockchain address
type GetTopNDexsForNetworkEthereumDexTradesExchangeEthereumDexAddress struct {
	// String address representation
	Address string `json:"address"`
}

// GetAddress returns GetTopNDexsForNetworkEthereumDexTradesExchangeEthereumDexAddress.Address, and is useful for accessing the field via an interface.
func (v *GetTopNDexsForNetworkEthereumDexTradesExchangeEthereumDexAddress) GetAddress() string {
	return v.Address
}

// GetTopNDexsForNetworkResponse is returned by GetTopNDexsForNetwork on success.
type GetTopNDexsForNetworkResponse struct {
	// Ethereum Mainnet / Classic Chain Datasets
	Ethereum GetTopNDexsForNetworkEthereum `json:"ethereum"`
}

// GetEthereum returns GetTopNDexsForNetworkResponse.Ethereum, and is useful for accessing the field via an interface.
func (v *GetTopNDexsForNetworkResponse) GetEthereum() GetTopNDexsForNetworkEthereum {
	return v.Ethereum
}

// __GetAllStablecoinPairsCreatedForDexInput is used internally by genqlient
type __GetAllStablecoinPairsCreatedForDexInput struct {
	Network           EthereumNetwork `json:"network"`
	From              time.Time       `json:"from"`
	Limit             int             `json:"limit"`
	FactoryAddress    string          `json:"factoryAddress"`
	StablecoinAddress string          `json:"stablecoinAddress"`
	TradeAmountUsd    float64         `json:"tradeAmountUsd"`
}

// GetNetwork returns __GetAllStablecoinPairsCreatedForDexInput.Network, and is useful for accessing the field via an interface.
func (v *__GetAllStablecoinPairsCreatedForDexInput) GetNetwork() EthereumNetwork { return v.Network }

// GetFrom returns __GetAllStablecoinPairsCreatedForDexInput.From, and is useful for accessing the field via an interface.
func (v *__GetAllStablecoinPairsCreatedForDexInput) GetFrom() time.Time { return v.From }

// GetLimit returns __GetAllStablecoinPairsCreatedForDexInput.Limit, and is useful for accessing the field via an interface.
func (v *__GetAllStablecoinPairsCreatedForDexInput) GetLimit() int { return v.Limit }

// GetFactoryAddress returns __GetAllStablecoinPairsCreatedForDexInput.FactoryAddress, and is useful for accessing the field via an interface.
func (v *__GetAllStablecoinPairsCreatedForDexInput) GetFactoryAddress() string {
	return v.FactoryAddress
}

// GetStablecoinAddress returns __GetAllStablecoinPairsCreatedForDexInput.StablecoinAddress, and is useful for accessing the field via an interface.
func (v *__GetAllStablecoinPairsCreatedForDexInput) GetStablecoinAddress() string {
	return v.StablecoinAddress
}

// GetTradeAmountUsd returns __GetAllStablecoinPairsCreatedForDexInput.TradeAmountUsd, and is useful for accessing the field via an interface.
func (v *__GetAllStablecoinPairsCreatedForDexInput) GetTradeAmountUsd() float64 {
	return v.TradeAmountUsd
}

// __GetBitQueryAccountDetailsInput is used internally by genqlient
type __GetBitQueryAccountDetailsInput struct {
	ApiKey string `json:"apiKey"`
}

// GetApiKey returns __GetBitQueryAccountDetailsInput.ApiKey, and is useful for accessing the field via an interface.
func (v *__GetBitQueryAccountDetailsInput) GetApiKey() string { return v.ApiKey }

// __GetPairCreatedByFactoryInput is used internally by genqlient
type __GetPairCreatedByFactoryInput struct {
	Network        EthereumNetwork `json:"network"`
	Limit          int             `json:"limit"`
	FactoryAddress string          `json:"factoryAddress"`
}

// GetNetwork returns __GetPairCreatedByFactoryInput.Network, and is useful for accessing the field via an interface.
func (v *__GetPairCreatedByFactoryInput) GetNetwork() EthereumNetwork { return v.Network }

// GetLimit returns __GetPairCreatedByFactoryInput.Limit, and is useful for accessing the field via an interface.
func (v *__GetPairCreatedByFactoryInput) GetLimit() int { return v.Limit }

// GetFactoryAddress returns __GetPairCreatedByFactoryInput.FactoryAddress, and is useful for accessing the field via an interface.
func (v *__GetPairCreatedByFactoryInput) GetFactoryAddress() string { return v.FactoryAddress }

// __GetRouterAddressFromPairBaseCurrencysInput is used internally by genqlient
type __GetRouterAddressFromPairBaseCurrencysInput struct {
	Network        EthereumNetwork `json:"network"`
	FactoryAddress string          `json:"factoryAddress"`
	TokenAddresses []string        `json:"tokenAddresses"`
	Limit          int             `json:"limit"`
}

// GetNetwork returns __GetRouterAddressFromPairBaseCurrencysInput.Network, and is useful for accessing the field via an interface.
func (v *__GetRouterAddressFromPairBaseCurrencysInput) GetNetwork() EthereumNetwork { return v.Network }

// GetFactoryAddress returns __GetRouterAddressFromPairBaseCurrencysInput.FactoryAddress, and is useful for accessing the field via an interface.
func (v *__GetRouterAddressFromPairBaseCurrencysInput) GetFactoryAddress() string {
	return v.FactoryAddress
}

// GetTokenAddresses returns __GetRouterAddressFromPairBaseCurrencysInput.TokenAddresses, and is useful for accessing the field via an interface.
func (v *__GetRouterAddressFromPairBaseCurrencysInput) GetTokenAddresses() []string {
	return v.TokenAddresses
}

// GetLimit returns __GetRouterAddressFromPairBaseCurrencysInput.Limit, and is useful for accessing the field via an interface.
func (v *__GetRouterAddressFromPairBaseCurrencysInput) GetLimit() int { return v.Limit }

// __GetTopNDexsForNetworkInput is used internally by genqlient
type __GetTopNDexsForNetworkInput struct {
	Network EthereumNetwork `json:"network"`
	Limit   int             `json:"limit"`
	Offset  int             `json:"offset"`
	From    time.Time       `json:"from"`
}

// GetNetwork returns __GetTopNDexsForNetworkInput.Network, and is useful for accessing the field via an interface.
func (v *__GetTopNDexsForNetworkInput) GetNetwork() EthereumNetwork { return v.Network }

// GetLimit returns __GetTopNDexsForNetworkInput.Limit, and is useful for accessing the field via an interface.
func (v *__GetTopNDexsForNetworkInput) GetLimit() int { return v.Limit }

// GetOffset returns __GetTopNDexsForNetworkInput.Offset, and is useful for accessing the field via an interface.
func (v *__GetTopNDexsForNetworkInput) GetOffset() int { return v.Offset }

// GetFrom returns __GetTopNDexsForNetworkInput.From, and is useful for accessing the field via an interface.
func (v *__GetTopNDexsForNetworkInput) GetFrom() time.Time { return v.From }

func GetAllStablecoinPairsCreatedForDex(
	ctx context.Context,
	client graphql.Client,
	network EthereumNetwork,
	from time.Time,
	limit int,
	factoryAddress string,
	stablecoinAddress string,
	tradeAmountUsd float64,
) (*GetAllStablecoinPairsCreatedForDexResponse, error) {
	req := &graphql.Request{
		OpName: "GetAllStablecoinPairsCreatedForDex",
		Query: `
query GetAllStablecoinPairsCreatedForDex ($network: EthereumNetwork!, $from: ISO8601DateTime, $limit: Int!, $factoryAddress: String!, $stablecoinAddress: String!, $tradeAmountUsd: Float!) {
	ethereum(network: $network) {
		dexTrades(options: {asc:"timeInterval.second",limit:$limit}, time: {after:$from}, exchangeAddress: {is:$factoryAddress}, quoteCurrency: {is:$stablecoinAddress}, tradeAmountUsd: {gt:$tradeAmountUsd}) {
			timeInterval {
				second(count: 60)
			}
			baseCurrency {
				symbol
				address
			}
			baseAmount
			quoteCurrency {
				symbol
				address
			}
			quoteAmount
			trades: count
			quotePrice
			high: quotePrice(calculate: maximum)
			low: quotePrice(calculate: minimum)
			open: minimum(of: block, get: quote_price)
			close: maximum(of: block, get: quote_price)
			volume: quoteAmount
			count
		}
	}
}
`,
		Variables: &__GetAllStablecoinPairsCreatedForDexInput{
			Network:           network,
			From:              from,
			Limit:             limit,
			FactoryAddress:    factoryAddress,
			StablecoinAddress: stablecoinAddress,
			TradeAmountUsd:    tradeAmountUsd,
		},
	}
	var err error

	var data GetAllStablecoinPairsCreatedForDexResponse
	resp := &graphql.Response{Data: &data}

	err = client.MakeRequest(
		ctx,
		req,
		resp,
	)

	return &data, err
}

func GetBitQueryAccountDetails(
	ctx context.Context,
	client graphql.Client,
	apiKey string,
) (*GetBitQueryAccountDetailsResponse, error) {
	req := &graphql.Request{
		OpName: "GetBitQueryAccountDetails",
		Query: `
query GetBitQueryAccountDetails ($apiKey: String!) {
	utilities {
		activePeriod(apiKey: $apiKey) {
			pointsRemaining
			points
			isPaid
			isPointsConsumed
			isSpent
			isBlocked
			starts {
				date
			}
			ends {
				date
			}
			billingDay
		}
	}
}
`,
		Variables: &__GetBitQueryAccountDetailsInput{
			ApiKey: apiKey,
		},
	}
	var err error

	var data GetBitQueryAccountDetailsResponse
	resp := &graphql.Response{Data: &data}

	err = client.MakeRequest(
		ctx,
		req,
		resp,
	)

	return &data, err
}

func GetPairCreatedByFactory(
	ctx context.Context,
	client graphql.Client,
	network EthereumNetwork,
	limit int,
	factoryAddress string,
) (*GetPairCreatedByFactoryResponse, error) {
	req := &graphql.Request{
		OpName: "GetPairCreatedByFactory",
		Query: `
query GetPairCreatedByFactory ($network: EthereumNetwork!, $limit: Int!, $factoryAddress: String!) {
	ethereum(network: $network) {
		arguments(smartContractAddress: {is:$factoryAddress}, smartContractEvent: {is:"PairCreated"}, options: {desc:"block.height",limit:$limit}) {
			reference {
				address
			}
			block {
				height
			}
		}
	}
}
`,
		Variables: &__GetPairCreatedByFactoryInput{
			Network:        network,
			Limit:          limit,
			FactoryAddress: factoryAddress,
		},
	}
	var err error

	var data GetPairCreatedByFactoryResponse
	resp := &graphql.Response{Data: &data}

	err = client.MakeRequest(
		ctx,
		req,
		resp,
	)

	return &data, err
}

func GetRouterAddressFromPairBaseCurrencys(
	ctx context.Context,
	client graphql.Client,
	network EthereumNetwork,
	factoryAddress string,
	tokenAddresses []string,
	limit int,
) (*GetRouterAddressFromPairBaseCurrencysResponse, error) {
	req := &graphql.Request{
		OpName: "GetRouterAddressFromPairBaseCurrencys",
		Query: `
query GetRouterAddressFromPairBaseCurrencys ($network: EthereumNetwork!, $factoryAddress: String!, $tokenAddresses: [String!], $limit: Int!) {
	ethereum(network: $network) {
		dexTrades(options: {limit:$limit,desc:"block.height"}, baseCurrency: {in:$tokenAddresses}, exchangeAddress: {is:$factoryAddress}) {
			block {
				height
			}
			transaction {
				to {
					address
				}
			}
		}
	}
}
`,
		Variables: &__GetRouterAddressFromPairBaseCurrencysInput{
			Network:        network,
			FactoryAddress: factoryAddress,
			TokenAddresses: tokenAddresses,
			Limit:          limit,
		},
	}
	var err error

	var data GetRouterAddressFromPairBaseCurrencysResponse
	resp := &graphql.Response{Data: &data}

	err = client.MakeRequest(
		ctx,
		req,
		resp,
	)

	return &data, err
}

func GetTopNDexsForNetwork(
	ctx context.Context,
	client graphql.Client,
	network EthereumNetwork,
	limit int,
	offset int,
	from time.Time,
) (*GetTopNDexsForNetworkResponse, error) {
	req := &graphql.Request{
		OpName: "GetTopNDexsForNetwork",
		Query: `
query GetTopNDexsForNetwork ($network: EthereumNetwork!, $limit: Int!, $offset: Int!, $from: ISO8601DateTime) {
	ethereum(network: $network) {
		dexTrades(options: {desc:"trades",limit:$limit,offset:$offset}, date: {since:$from}, protocol: {is:"Uniswap v2"}) {
			protocol
			trades: count
			currencies: count(uniq: buy_currency)
			contracts: count(uniq: smart_contracts)
			exchange {
				fullName
				address {
					address
				}
			}
		}
	}
}
`,
		Variables: &__GetTopNDexsForNetworkInput{
			Network: network,
			Limit:   limit,
			Offset:  offset,
			From:    from,
		},
	}
	var err error

	var data GetTopNDexsForNetworkResponse
	resp := &graphql.Response{Data: &data}

	err = client.MakeRequest(
		ctx,
		req,
		resp,
	)

	return &data, err
}
